import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Sample parts data for Parts List (using Part model)
const partsData = [
  {
    partNo: 'AF-001-2024',
    masterPartNo: 'MP-AF-001',
    brand: 'Mann Filter',
    description: 'Air Filter Element - Premium Quality',
    mainCategory: 'Engine Parts',
    subCategory: 'Filters',
    application: 'Universal Application',
    hsCode: '8421.23.00',
    uom: 'PCS',
    weight: 0.5,
    reOrderLevel: 50,
    cost: 15.00,
    priceA: 22.50,
    priceB: 19.50,
    priceM: 18.00,
    rackNo: 'A-01-01',
    origin: 'Germany',
    grade: 'A',
    status: 'A',
    smc: 'SMC-AF-001',
    size: 'Standard',
    remarks: 'High quality air filter element',
    stockQuantity: 85
  },
  {
    partNo: 'TB-002-2024',
    masterPartNo: 'MP-TB-002',
    brand: 'Gates',
    description: 'Timing Belt - Multi-Rib',
    mainCategory: 'Engine Parts',
    subCategory: 'Belts',
    application: 'Universal Application',
    hsCode: '4010.39.00',
    uom: 'PCS',
    weight: 0.8,
    reOrderLevel: 30,
    cost: 35.00,
    priceA: 52.50,
    priceB: 45.50,
    priceM: 42.00,
    rackNo: 'A-02-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-TB-002',
    size: 'Standard',
    remarks: 'High-quality timing belt',
    stockQuantity: 72
  },
  {
    partNo: 'WP-003-2024',
    masterPartNo: 'MP-WP-003',
    brand: 'Fel-Pro',
    description: 'Water Pump Gasket - Premium',
    mainCategory: 'Cooling System',
    subCategory: 'Gaskets',
    application: 'Universal Application',
    hsCode: '8481.80.90',
    uom: 'PCS',
    weight: 0.1,
    reOrderLevel: 40,
    cost: 8.50,
    priceA: 12.75,
    priceB: 11.00,
    priceM: 10.00,
    rackNo: 'B-01-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-WP-003',
    size: 'Standard',
    remarks: 'Premium water pump gasket',
    stockQuantity: 95
  },
  {
    partNo: 'RC-004-2024',
    masterPartNo: 'MP-RC-004',
    brand: 'Stant',
    description: 'Radiator Cap - 16 PSI',
    mainCategory: 'Cooling System',
    subCategory: 'Caps',
    application: 'Universal Application',
    hsCode: '8481.80.90',
    uom: 'PCS',
    weight: 0.2,
    reOrderLevel: 60,
    cost: 6.00,
    priceA: 9.00,
    priceB: 7.50,
    priceM: 7.00,
    rackNo: 'B-02-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-RC-004',
    size: '16 PSI',
    remarks: 'Standard radiator cap',
    stockQuantity: 120
  },
  {
    partNo: 'CT-005-2024',
    masterPartNo: 'MP-CT-005',
    brand: 'Standard Motor',
    description: 'Coolant Temperature Sensor',
    mainCategory: 'Cooling System',
    subCategory: 'Sensors',
    application: 'Universal Application',
    hsCode: '9026.10.00',
    uom: 'PCS',
    weight: 0.15,
    reOrderLevel: 35,
    cost: 22.00,
    priceA: 33.00,
    priceB: 28.50,
    priceM: 26.00,
    rackNo: 'C-01-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-CT-005',
    size: 'Standard',
    remarks: 'Precision coolant temperature sensor',
    stockQuantity: 68
  },
  {
    partNo: 'IC-006-2024',
    masterPartNo: 'MP-IC-006',
    brand: 'Delphi',
    description: 'Ignition Coil - High Performance',
    mainCategory: 'Engine Parts',
    subCategory: 'Ignition',
    application: 'Universal Application',
    hsCode: '8511.10.00',
    uom: 'PCS',
    weight: 0.6,
    reOrderLevel: 25,
    cost: 45.00,
    priceA: 67.50,
    priceB: 58.50,
    priceM: 54.00,
    rackNo: 'C-02-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-IC-006',
    size: 'Standard',
    remarks: 'High-performance ignition coil',
    stockQuantity: 55
  },
  {
    partNo: 'FP-007-2024',
    masterPartNo: 'MP-FP-007',
    brand: 'Bosch',
    description: 'Fuel Pump - Electric',
    mainCategory: 'Fuel System',
    subCategory: 'Pumps',
    application: 'Universal Application',
    hsCode: '8413.30.00',
    uom: 'PCS',
    weight: 1.2,
    reOrderLevel: 20,
    cost: 85.00,
    priceA: 127.50,
    priceB: 110.50,
    priceM: 102.00,
    rackNo: 'D-01-01',
    origin: 'Germany',
    grade: 'A',
    status: 'A',
    smc: 'SMC-FP-007',
    size: 'Standard',
    remarks: 'Reliable electric fuel pump',
    stockQuantity: 42
  },
  {
    partNo: 'MA-008-2024',
    masterPartNo: 'MP-MA-008',
    brand: 'Denso',
    description: 'Mass Air Flow Sensor',
    mainCategory: 'Engine Parts',
    subCategory: 'Sensors',
    application: 'Universal Application',
    hsCode: '9026.10.00',
    uom: 'PCS',
    weight: 0.3,
    reOrderLevel: 30,
    cost: 65.00,
    priceA: 97.50,
    priceB: 84.50,
    priceM: 78.00,
    rackNo: 'D-02-01',
    origin: 'Japan',
    grade: 'A',
    status: 'A',
    smc: 'SMC-MA-008',
    size: 'Standard',
    remarks: 'Precise mass air flow sensor',
    stockQuantity: 38
  },
  {
    partNo: 'TP-009-2024',
    masterPartNo: 'MP-TP-009',
    brand: 'Standard Motor',
    description: 'Throttle Position Sensor',
    mainCategory: 'Engine Parts',
    subCategory: 'Sensors',
    application: 'Universal Application',
    hsCode: '9026.10.00',
    uom: 'PCS',
    weight: 0.2,
    reOrderLevel: 35,
    cost: 28.00,
    priceA: 42.00,
    priceB: 36.40,
    priceM: 33.60,
    rackNo: 'E-01-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-TP-009',
    size: 'Standard',
    remarks: 'Accurate throttle position sensor',
    stockQuantity: 62
  },
  {
    partNo: 'CP-010-2024',
    masterPartNo: 'MP-CP-010',
    brand: 'Delphi',
    description: 'Camshaft Position Sensor',
    mainCategory: 'Engine Parts',
    subCategory: 'Sensors',
    application: 'Universal Application',
    hsCode: '9026.10.00',
    uom: 'PCS',
    weight: 0.25,
    reOrderLevel: 30,
    cost: 32.00,
    priceA: 48.00,
    priceB: 41.60,
    priceM: 38.40,
    rackNo: 'E-02-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-CP-010',
    size: 'Standard',
    remarks: 'Reliable camshaft position sensor',
    stockQuantity: 58
  },
  {
    partNo: 'CR-011-2024',
    masterPartNo: 'MP-CR-011',
    brand: 'Standard Motor',
    description: 'Crankshaft Position Sensor',
    mainCategory: 'Engine Parts',
    subCategory: 'Sensors',
    application: 'Universal Application',
    hsCode: '9026.10.00',
    uom: 'PCS',
    weight: 0.3,
    reOrderLevel: 30,
    cost: 38.00,
    priceA: 57.00,
    priceB: 49.40,
    priceM: 45.60,
    rackNo: 'F-01-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-CR-011',
    size: 'Standard',
    remarks: 'Precise crankshaft position sensor',
    stockQuantity: 51
  },
  {
    partNo: 'IA-012-2024',
    masterPartNo: 'MP-IA-012',
    brand: 'ACDelco',
    description: 'Idle Air Control Valve',
    mainCategory: 'Engine Parts',
    subCategory: 'Valves',
    application: 'Universal Application',
    hsCode: '8481.80.90',
    uom: 'PCS',
    weight: 0.4,
    reOrderLevel: 25,
    cost: 55.00,
    priceA: 82.50,
    priceB: 71.50,
    priceM: 66.00,
    rackNo: 'F-02-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-IA-012',
    size: 'Standard',
    remarks: 'Efficient idle air control valve',
    stockQuantity: 47
  },
  {
    partNo: 'EG-013-2024',
    masterPartNo: 'MP-EG-013',
    brand: 'Standard Motor',
    description: 'EGR Valve - Exhaust Gas Recirculation',
    mainCategory: 'Engine Parts',
    subCategory: 'Valves',
    application: 'Universal Application',
    hsCode: '8481.80.90',
    uom: 'PCS',
    weight: 0.5,
    reOrderLevel: 20,
    cost: 68.00,
    priceA: 102.00,
    priceB: 88.40,
    priceM: 81.60,
    rackNo: 'G-01-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-EG-013',
    size: 'Standard',
    remarks: 'Efficient EGR valve',
    stockQuantity: 33
  },
  {
    partNo: 'PC-014-2024',
    masterPartNo: 'MP-PC-014',
    brand: 'ACDelco',
    description: 'PCV Valve - Positive Crankcase Ventilation',
    mainCategory: 'Engine Parts',
    subCategory: 'Valves',
    application: 'Universal Application',
    hsCode: '8481.80.90',
    uom: 'PCS',
    weight: 0.1,
    reOrderLevel: 50,
    cost: 12.00,
    priceA: 18.00,
    priceB: 15.60,
    priceM: 14.40,
    rackNo: 'G-02-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-PC-014',
    size: 'Standard',
    remarks: 'Standard PCV valve',
    stockQuantity: 88
  },
  {
    partNo: 'OP-015-2024',
    masterPartNo: 'MP-OP-015',
    brand: 'Standard Motor',
    description: 'Oil Pressure Sensor',
    mainCategory: 'Engine Parts',
    subCategory: 'Sensors',
    application: 'Universal Application',
    hsCode: '9026.10.00',
    uom: 'PCS',
    weight: 0.2,
    reOrderLevel: 40,
    cost: 25.00,
    priceA: 37.50,
    priceB: 32.50,
    priceM: 30.00,
    rackNo: 'H-01-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-OP-015',
    size: 'Standard',
    remarks: 'Accurate oil pressure sensor',
    stockQuantity: 76
  },
  {
    partNo: 'KN-016-2024',
    masterPartNo: 'MP-KN-016',
    brand: 'Delphi',
    description: 'Knock Sensor',
    mainCategory: 'Engine Parts',
    subCategory: 'Sensors',
    application: 'Universal Application',
    hsCode: '9026.10.00',
    uom: 'PCS',
    weight: 0.25,
    reOrderLevel: 30,
    cost: 42.00,
    priceA: 63.00,
    priceB: 54.60,
    priceM: 50.40,
    rackNo: 'H-02-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-KN-016',
    size: 'Standard',
    remarks: 'Sensitive knock sensor',
    stockQuantity: 59
  },
  {
    partNo: 'MP-017-2024',
    masterPartNo: 'MP-MP-017',
    brand: 'Standard Motor',
    description: 'MAP Sensor - Manifold Absolute Pressure',
    mainCategory: 'Engine Parts',
    subCategory: 'Sensors',
    application: 'Universal Application',
    hsCode: '9026.10.00',
    uom: 'PCS',
    weight: 0.2,
    reOrderLevel: 35,
    cost: 35.00,
    priceA: 52.50,
    priceB: 45.50,
    priceM: 42.00,
    rackNo: 'I-01-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-MP-017',
    size: 'Standard',
    remarks: 'Precise MAP sensor',
    stockQuantity: 64
  },
  {
    partNo: 'IM-018-2024',
    masterPartNo: 'MP-IM-018',
    brand: 'Fel-Pro',
    description: 'Intake Manifold Gasket',
    mainCategory: 'Engine Parts',
    subCategory: 'Gaskets',
    application: 'Universal Application',
    hsCode: '8481.80.90',
    uom: 'PCS',
    weight: 0.3,
    reOrderLevel: 40,
    cost: 18.00,
    priceA: 27.00,
    priceB: 23.40,
    priceM: 21.60,
    rackNo: 'I-02-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-IM-018',
    size: 'Standard',
    remarks: 'Durable intake manifold gasket',
    stockQuantity: 82
  },
  {
    partNo: 'EM-019-2024',
    masterPartNo: 'MP-EM-019',
    brand: 'Fel-Pro',
    description: 'Exhaust Manifold Gasket',
    mainCategory: 'Engine Parts',
    subCategory: 'Gaskets',
    application: 'Universal Application',
    hsCode: '8481.80.90',
    uom: 'PCS',
    weight: 0.35,
    reOrderLevel: 35,
    cost: 22.00,
    priceA: 33.00,
    priceB: 28.60,
    priceM: 26.40,
    rackNo: 'J-01-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-EM-019',
    size: 'Standard',
    remarks: 'Heat-resistant exhaust manifold gasket',
    stockQuantity: 71
  },
  {
    partNo: 'VC-020-2024',
    masterPartNo: 'MP-VC-020',
    brand: 'Fel-Pro',
    description: 'Valve Cover Gasket',
    mainCategory: 'Engine Parts',
    subCategory: 'Gaskets',
    application: 'Universal Application',
    hsCode: '8481.80.90',
    uom: 'PCS',
    weight: 0.2,
    reOrderLevel: 45,
    cost: 15.00,
    priceA: 22.50,
    priceB: 19.50,
    priceM: 18.00,
    rackNo: 'J-02-01',
    origin: 'USA',
    grade: 'A',
    status: 'A',
    smc: 'SMC-VC-020',
    size: 'Standard',
    remarks: 'Reliable valve cover gasket',
    stockQuantity: 93
  },
];

async function add20PartsToList() {
  console.log('🌱 Adding 20 parts to Parts List...\n');

  try {
    const createdParts = [];

    for (const partData of partsData) {
      const { stockQuantity, ...partFields } = partData;

      // Check if part already exists
      const existingPart = await prisma.part.findUnique({
        where: { partNo: partData.partNo }
      });

      if (existingPart) {
        console.log(`   ⚠️  Part ${partData.partNo} already exists, skipping...`);
        continue;
      }

      // Create the part
      const part = await prisma.part.create({
        data: partFields
      });

      // Create stock entry
      await prisma.stock.create({
        data: {
          partId: part.id,
          quantity: stockQuantity,
          location: `Warehouse ${partData.rackNo.split('-')[0]}`
        }
      });

      createdParts.push(part);
      console.log(`   ✓ Created: ${part.partNo} - ${part.description}`);
    }

    console.log(`\n✅ Successfully added ${createdParts.length} parts to Parts List!`);
    console.log(`\n📋 Summary:`);
    console.log(`   - Parts Created: ${createdParts.length}`);
    console.log(`   - Total Parts in Database: ${await prisma.part.count()}`);

  } catch (error) {
    console.error('❌ Error adding parts:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run the function
if (require.main === module) {
  add20PartsToList()
    .then(() => {
      console.log('\n✅ Script completed successfully!');
      process.exit(0);
    })
    .catch((error) => {
      console.error('\n❌ Script failed:', error);
      process.exit(1);
    });
}

export { add20PartsToList };

